server:
  port: 8082

spring:
  application:
    name: user-portfolio-service
  cloud:
    discovery:
      enabled: false

  # 1. Configuração do Banco de Dados
  datasource:
    url: jdbc:postgresql://localhost:5434/portfoliodb
    username: portfoliouser
    password: portfoliopassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 2. Configuração da Mensageria Assíncrona
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
